from __future__ import annotations

from typing import Any


def test_request_id_header_propagated_when_provided(client: Any) -> None:
    r = client.get("/healthz", headers={"X-Request-ID": "test-abc-123"})
    assert r.status_code == 200
    assert r.headers.get("X-Request-ID") == "test-abc-123"


def test_request_id_autogenerated_when_missing(client: Any) -> None:
    r = client.get("/healthz")
    assert r.status_code == 200
    rid = r.headers.get("X-Request-ID")
    assert rid is not None
    assert len(rid) == 16


def test_request_id_unique_across_requests(client: Any) -> None:
    rid1 = client.get("/healthz").headers.get("X-Request-ID")
    rid2 = client.get("/healthz").headers.get("X-Request-ID")
    assert rid1 != rid2


def test_request_id_present_on_authenticated_endpoint(client: Any) -> None:
    r = client.get("/sources")
    assert r.status_code == 200
    assert r.headers.get("X-Request-ID") is not None
